### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by mejje** [Benedictt/Skypedotnet#1]
Hi, I'm interested in this project, do you need help?

**Comment by Benedictt** [comment]
Hi! As you can see - development is in very early stage currently. Actually what is done is only authorization with skype for web (which is in beta for the moment). We use non-public api for it. You can help with researching this api if you have skype for web account, or porting source code from skypeweb plugin for pidgin (it's written in C, I added [its sources](https://github.com/Benedictt/Skypedotnet/tree/master/skypeweb_src) to this repository temporary. )
